name: Python Lint Check

# This action runs on every push to the main branch
# and on every pull request that targets the main branch.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get a copy of your code from the repository
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install the linter tool (flake8)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      # Step 4: Run the linter to check for errors and style issues
      - name: Lint with flake8
        run: |
          # Run flake8. It will automatically fail the action if it finds any issues.
          # --max-line-length=120 is a common setting for modern projects.
          flake8 tunnel-manager.py --count --show-source --statistics --max-line-length=120
